version: '3.8'

services:

  keycloak-postgres:
    image: ${KEYCLOAK_POSTGRES_IMAGE}
    container_name: postgres-keycloak
    volumes:
      - keycloak_postgres_data1:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U ${KEYCLOAK_POSTGRES_USER} && psql -d ${KEYCLOAK_POSTGRES_DB} -U ${KEYCLOAK_POSTGRES_USER} -c "SELECT 1=1"
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: ${KEYCLOAK_IMAGE}
    container_name: keycloak
    volumes:
      - ./keycloak/:/opt/jboss/keycloak/imports1/
    #      - ./wait-for-it.sh:/opt/jboss/keycloak/imports1/wait-for-it.sh
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports1/realm-export.json"
    env_file:
      - .env
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: ${KEYCLOAK_POSTGRES_DB}
      DB_USER: ${KEYCLOAK_POSTGRES_USER}
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}
    depends_on:
      - keycloak-postgres

volumes:
  keycloak_postgres_data1:
