version: '3.8'

# starts 1 docker container running minio server instances.
services:
  elk:
    image: ${ELK_IMAGE}
    container_name: elk
    ports:
      - ${KIBANA_PORT}
      - ${ELASTICSEARCH_PORT}
      - ${LOGSTASH_PORT}
    env_file:
      - .env
    environment:
      - LOGSTASH_START=1
      - KIBANA_START=1
      - ELASTICSEARCH_START=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elk:9200/"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data: