version: '3.8'

# starts 1 docker container running minio server instances.
services:
  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    env_file:
      - .env
    environment:
      - LOGSTASH_START=1
      - KIBANA_START=1
      - ELASTICSEARCH_START=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elk:9200/"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data: