version: '3.8'

# starts 1 docker container running minio server instances.
services:
  minio:
    image: ${MINIO_IMAGE}
    container_name: minio
    volumes:
      - minio_data:${VOLUME_PATH}
    ports:
      - ${MINIO_PORT}
    env_file:
      - .env
    command: server ${VOLUME_PATH}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data: